# Generated by Django 6.0.7 on 2026-07-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="tweet",
            new_name="text",
        ),
    ]
